SELECT
ME_NAME
FROM MEMBER
WHERE ME_ID = 'ADMIN';
COMMIT;
SELECT FO_FILENAME,FO_NAME,FO_COMMENT FROM FOODS;
INSERT INTO STORE VALUES('ICND011','02','디저트','인천광역시 중구 한로','디저트 전문 식당','01015881588','L');

INSERT INTO COMMUNITY VALUES('TEST',79,SYSDATE,'EGEWG','ERG.JPG','제목'); 
CREATE OR REPLACE FORCE VIEW BOARDVIEW AS 
SELECT CO_NUM,ME_NAME,CO_MEID,CO_TITLE,CO_COMMENT,CO_DATE,CO_FILE, ROW_NUMBER() OVER(ORDER BY CO_NUM DESC) AS RN
FROM COMMUNITY INNER JOIN MEMBER ON ME_ID=CO_MEID;



CREATE OR REPLACE VIEW COMMUNITYTHUMBS AS
SELECT *
FROM (SELECT
    SUM(TH_STATE) AS TOP,CO_NUM,CO_MEID AS ID ,CO_MEID,ROW_NUMBER() OVER(ORDER BY CO_DATE DESC) AS RN,CO_TITLE,CO_COMMENT,CO_DATE,CO_FILE
    FROM THUMBS FULL OUTER JOIN COMMUNITY ON CO_NUM=TH_CONUM
    GROUP BY CO_NUM,CO_MEID,CO_TITLE,CO_COMMENT,CO_DATE,CO_FILE) DD INNER JOIN MEMBER ON DD.ID=ME_ID
    ;
    COMMIT;
    
    --TOP 3
    SELECT *
    FROM(SELECT
        *
    FROM COMMUNITYTHUMBS
    ORDER BY TOP DESC)
    WHERE TOP IS NOT NULL AND ROWNUM BETWEEN 1 AND 3;
    
    -- 목록 NULL이면 IF문으로 0으로 정해줌
    SELECT
        *
    FROM COMMUNITYTHUMBS;
    
    
    SELECT
        *
    FROM THUMBS;

COMMIT;


--
--  CREATE OR REPLACE FORCE VIEW "PROJECT_DBA"."THUMBVIEW" ("CO_MEID", "CO_NUM", "CO_DATE", "CO_COMMENT", "CO_THUMB", "CO_FILE", "CO_TITLE", "ME_NAME", "LIST") AS 
--  SELECT CO_MEID,
--        CO_NUM,
--        CO_DATE,
--        CO_COMMENT,
--        CO_THUMB,
--        CO_FILE,
--        CO_TITLE,
--        ME_NAME,
--         RANK() OVER(PARTITION BY 1 ORDER BY CO_THUMB DESC) AS LIST        
--        FROM COMMUNITY
--        
--INNER JOIN "MEMBER" ON CO_MEID = ME_ID;
--
SELECT COUNT(*) FROM THUMBS WHERE TH_MEID='TEST' AND TH_CONUM=30;

SELECT COUNT(*) FROM THUMBS WHERE TH_MEID='TEST' AND TH_CONUM=30;

INSERT INTO THUMBS VALUES('TEST','TEST',1,SYSDATE,30);
SELECT
    *
FROM thumbs;















SELECT
  *
FROM STORE;
COMMIT;
DELETE STORE WHERE ST_COMMENT LIKE '%디저트%';
INSERT INTO STORE VALUES('ICND003','02','디저트','인천광역시 중구 한로','디저트 전문 식당','01040343534','L');

 